#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Suzuha Kiuchi
import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.sydin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
